### ISSUE TITLE
Add base README

### ISSUE THREAD

**Issue by azinit** [martis-git/actool-cli#1]
## TODO
- [x] add section: **description** (Ilya)
   - base and short description
- [x] add section: **table of contents** (Ilya)
   - auto computed table of contents off README
- [x] add section: **overview** (Ilya)
   - +- short explanation of problem and little more details about solution
- [ ] add section: **get started** (Damir)
   - quick start with module (how it should be - by your opinion)
    - [ ]  add section: **installing** 
       - installing process (yarn + npm)
    - [ ] add section: **usage example**
       - quick usage example (import / require without custom config)
- [ ] add section: **configuration**
   - customization for project (how it should be - by your opinion)
- [x] add section: **team** (Ilya)
   - look at examples (there are example with users badges)
- [ ] add section: **faq** (Ilya)
   - some specific cases / problems (how it should be - by your opinion)
- [x] add section: **plans** (Ilya)
   - about plans of product: script => npm module => vscode and etc.

## Followup (10.10.2020)
- https://www.notion.so/10-10-2020-Initial-meetup-045736bedac3492fabe734b705e77e9c

## Examples
- https://github.com/mapbox/mapbox-gl-js
- https://github.com/reduxjs/redux-toolkit
- https://github.com/commitizen/cz-cli
- https://github.com/eslint/eslint
- https://github.com/OpenAPITools/openapi-generator
- https://github.com/oreporan/color-tabs-vscode
- **https://github.com/vavilon-js/vavilon.js**
- **https://github.com/NickKaramoff/shareon**
- **https://github.com/NickKaramoff/vue-tinybox**
- **https://github.com/NickKaramoff/pretty-money**
- https://github.com/axios/axios
- https://github.com/reduxjs/redux-toolkit
- https://github.com/dotansimha/graphql-code-generator
- [and any othe opensource popular solution =) ]

**Comment by azinit** [comment]
take **description**, **overview** and **plans**

**Comment by lyf2000** [comment]
take **get started**

**Comment by azinit** [comment]
take **table of contents** too

**Comment by azinit** [comment]
take **team**

**Comment by martis-git** [comment]
take all...
![image](https://user-images.githubusercontent.com/42924400/95863401-cce32780-0d6c-11eb-8978-9c7b0693a6cd.png)
